# Generated by Django 3.1.1 on 2020-10-09 19:43

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20200914_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tweet.models.user_directory_path),
        ),
    ]
